default_platform(:android)

platform :android do
  desc "Build a release apk"
  lane :beta do
    sh "echo '>>>>>>>>>> Building release APK... <<<<<<<<<<'"
    sh "flutter clean"
    sh "flutter pub get"
    gradle(
      task: "clean assembleRelease",
      properties: {"applicationId" => "com.yomi.flutter_restaruant"}
      )
    # crashlytics
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
