// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAazLGDNd0sM6ixVxEIx0kSgRuJU1iAB4w',
    appId: '1:35224406241:android:00f352bb5d635a1b924fa0',
    messagingSenderId: '35224406241',
    projectId: 'findrestaurant-c80ea',
    databaseURL: 'https://findrestaurant-c80ea.firebaseio.com',
    storageBucket: 'findrestaurant-c80ea.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfe5kOHB_-GPPNovB8iCDimCBnTsW6OYQ',
    appId: '1:35224406241:ios:d8eb3d68795bc2d1924fa0',
    messagingSenderId: '35224406241',
    projectId: 'findrestaurant-c80ea',
    databaseURL: 'https://findrestaurant-c80ea.firebaseio.com',
    storageBucket: 'findrestaurant-c80ea.appspot.com',
    androidClientId: '35224406241-6hursinnrblkjo76gp1mlvppsddul6vu.apps.googleusercontent.com',
    iosClientId: '35224406241-8bh7hq1e07129nav2gcme5n9p565su7k.apps.googleusercontent.com',
    iosBundleId: 'com.yomi.find-restaurant',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTa69PL70CSycWl0J_hLml87LukfuTw9U',
    appId: '1:35224406241:web:cc49e6cf3d3c438d924fa0',
    messagingSenderId: '35224406241',
    projectId: 'findrestaurant-c80ea',
    authDomain: 'findrestaurant-c80ea.firebaseapp.com',
    databaseURL: 'https://findrestaurant-c80ea.firebaseio.com',
    storageBucket: 'findrestaurant-c80ea.appspot.com',
    measurementId: 'G-DR2KFBD7YK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnDjL5nQAx9jMzPIelhMt_eyMggq7lS3E',
    appId: '1:35224406241:ios:821bfd632df38e44924fa0',
    messagingSenderId: '35224406241',
    projectId: 'findrestaurant-c80ea',
    databaseURL: 'https://findrestaurant-c80ea.firebaseio.com',
    storageBucket: 'findrestaurant-c80ea.appspot.com',
    androidClientId: '35224406241-6hursinnrblkjo76gp1mlvppsddul6vu.apps.googleusercontent.com',
    iosClientId: '35224406241-ujri5q7pfruts9uerq1vbu6omoa6nk71.apps.googleusercontent.com',
    iosBundleId: 'com.yomi.find-restaurant.macos',
  );
}
