// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAazLGDNd0sM6ixVxEIx0kSgRuJU1iAB4w',
    appId: '1:35224406241:android:00f352bb5d635a1b924fa0',
    messagingSenderId: '35224406241',
    projectId: 'findrestaurant-c80ea',
    databaseURL: 'https://findrestaurant-c80ea.firebaseio.com',
    storageBucket: 'findrestaurant-c80ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfe5kOHB_-GPPNovB8iCDimCBnTsW6OYQ',
    appId: '1:35224406241:ios:d8eb3d68795bc2d1924fa0',
    messagingSenderId: '35224406241',
    projectId: 'findrestaurant-c80ea',
    databaseURL: 'https://findrestaurant-c80ea.firebaseio.com',
    storageBucket: 'findrestaurant-c80ea.appspot.com',
    androidClientId: '35224406241-90ngfgnmbfukjfedo8faa34kpt10vg46.apps.googleusercontent.com',
    iosClientId: '35224406241-8bh7hq1e07129nav2gcme5n9p565su7k.apps.googleusercontent.com',
    iosBundleId: 'com.yomi.find-restaurant',
  );
}
